spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/acblog?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # redis配置
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8       # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
    timeout: 10000

  # thymeleaf
  thymeleaf:
    cache: false # 禁用缓存



qiang:
  # session cache config
  shiro-redis:
    host: 127.0.0.1
    port: 6379
  # 文件路径
  file-path: /home/memo012/code/acblogMessage
  # druid 账号密码
  druid:
    user: admin
    password: acblogdev



# 控制台打印SQL语句
logging:
  level:
    root: info
    com.qiang.modules.sys.dao: trace
  pattern:
    console: '%p%m%n'